### ISSUE TITLE
ModuleNotFoundError: No module named 'desktop_cleaner'

### ISSUE THREAD

**Issue by khantanveer7** [KalleHallden/desktop_cleaner#8]
Traceback (most recent call last):
  File "cleandesk.py", line 5, in <module>
    import EventHandler
  File "/Users/khantanveer/Desktop/desktop_cleaner/EventHandler.py", line 7, in <module>
    from desktop_cleaner.extensions import extension_paths
ModuleNotFoundError: No module named 'desktop_cleaner'
![Screenshot 2020-05-08 at 11 14 41 PM](https://user-images.githubusercontent.com/57847199/81433197-c929f400-9181-11ea-952b-131bdea288a1.png)

**Comment by jpulley101** [comment]
<img width="443" alt="Screen Shot 2020-05-09 at 7 14 00 PM" src="https://user-images.githubusercontent.com/2576928/81487308-79066c80-9229-11ea-99c1-84f4c217358a.png">

<img width="593" alt="Screen Shot 2020-05-09 at 7 16 02 PM" src="https://user-images.githubusercontent.com/2576928/81487320-99362b80-9229-11ea-803b-45e418b5a48e.png">

This was my fix I also had to add the PYTHONPATH

**Comment by RmBau** [comment]
@jpulley101 
Not sure if I understand correctly. 
What else did you do to correct :No module named 'desktop_cleaner'?
